# this compose file is for testing purposes only
# use it for testing docker containsers built on local machine
version: "3"
services:
  dbgate:
    # build: docker
    image: dbgate/dbgate:beta-alpine
    restart: always
    ports:
      - 3100:3000
    # volumes:
    #   - /home/jena/dbgate-data:/root/dbgate-data

    volumes:
      - dbgate-data:/root/dbgate-data
    
    environment:
      WEB_ROOT: /dbgate

    # volumes:
    #   - /home/jena/test/chinook:/mnt/sqt
    # environment:
    #   CONNECTIONS: sqlite

    #   LABEL_sqlite: sqt
    #   FILE_sqlite: /mnt/sqt/Chinook.db
    #   ENGINE_sqlite: sqlite@dbgate-plugin-sqlite

volumes:
  dbgate-data:
    driver: local