name: Docker image

# on: [push]

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
    # - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

# on:
#   push:
#     branches:
#       - production

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-18.04]

    steps:
      - name: Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: yarn install
        run: |
          yarn install
      - name: setCurrentVersion
        run: |
          yarn setCurrentVersion
      - name: Prepare docker image
        run: |
          yarn run prepare:docker
      - name: Build docker image
        run: |
          docker build ./docker -t dbgate
      - name: Push docker image
        run: |
          docker tag dbgate dbgate/dbgate
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push dbgate/dbgate
      - name: Build alpine docker image
        run: |
          docker build ./docker -t dbgate -f docker/Dockerfile-alpine
      - name: Push alpine docker image
        run: |
          docker tag dbgate dbgate/dbgate:alpine
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push dbgate/dbgate:alpine
