name: Docker image

# on: [push]

on:
  push:
    branches:
      - production

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-18.04]
        # os: [macOS-10.14, windows-2016, ubuntu-18.04]

    steps:
      - name: Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: yarn install
        run: |
          yarn install
      - name: Prepare docker image
        run: |
          yarn run prepare:docker
      - name: Build docker image
        run: |
          docker build ./docker -t dbgate:future
      - name: Push docker image
        run: |
          docker tag dbgate:future dbgate/dbgate:future
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push dbgate/dbgate:future
